# Generated by Django 4.2.6 on 2024-01-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_alter_productionorder_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
    ]
