# Generated by Django 4.2.6 on 2024-01-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_remove_product_quantity_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='order_date',
        ),
    ]
