# Generated by Django 4.2.6 on 2023-12-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_remove_product_product_code_productionorder'),
        ('Inventory', '0002_rawmaterial_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialinventory',
            old_name='quantity',
            new_name='quantity_on_hand',
        ),
        migrations.RenameField(
            model_name='rawmaterialinventory',
            old_name='raw_material_id',
            new_name='raw_material',
        ),
        migrations.RenameField(
            model_name='rawmaterialinventory',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.warehouse')),
            ],
            options={
                'db_table': 'product_inventory',
            },
        ),
    ]
