# Generated by Django 4.2.6 on 2024-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_productrawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
