# Generated by Django 4.2.6 on 2024-01-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0002_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
    ]
