# Generated by Django 4.2.6 on 2024-01-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesOrder', '0002_remove_salesorder_product_remove_salesorder_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ship_date',
            field=models.DateField(),
        ),
    ]
